### ISSUE TITLE
/uses catHeading covers navBar

### ISSUE THREAD

**Issue by premiare** [whitep4nth3r/mk2-p4nth3rblog#119]
On the `/uses` route, the `.uses_catHeading` covers the `header` when scrolling down the page due to the same z-index value (10).

![image](https://github.com/whitep4nth3r/mk2-p4nth3rblog/assets/64188227/3adcd40f-06e3-48a4-9815-8a92a724be3e)

Not sure if intentional! Quick fix: changing z-index to 9 for `.uses_catHeading`
```css
.uses_catHeading {
  position: relative;
  top: 2.5rem;
  z-index: 9;
}
```

![image](https://github.com/whitep4nth3r/mk2-p4nth3rblog/assets/64188227/27ae194a-52fc-49ca-958c-8c81d78237d3)
